### ISSUE TITLE
Incompatible Vanilla Enchantments can still be applied with books.

### ISSUE THREAD

**Issue by terrasteel** [Athlaeos/EnchantsSquaredRewritten#10]
Hello,

While setting up my plugin I've noticed that incompatible-vanilla-enchantments doesn't actually render those enchantments always incompatible.

For example, I made Withering incompatible with Fire Aspect.
- When combining a Fire Aspect sword with a Withering sword, it won't succeed. (correct)
- When combining a Withering sword with a Fire Aspect sword, it won't succeed. (correct)
- When combining a Fire Aspect sword with a Withering book, it won't succeed. (correct)
- But, when combining a Withering sword with a Fire Aspect book, it succeeds. 

I know it isn't a config formatting issue since the other combinations succeed, as they should. It seems that using a book like this simply bypasses the restriction. Combining book on book also bypasses this restriction.
I've also noticed that this only applies when vanilla enchants are involved. Custom enchants work flawlessly for me.

Do you know why this might happen and how it could be fixed?
Thanks

**Comment by Athlaeos** [comment]
will investigate!
