### ISSUE TITLE
Metabolism is bugged

### ISSUE THREAD

**Issue by JasdanVM** [Athlaeos/EnchantsSquaredRewritten#13]
The enchantement works, but it shows no Text when applied to an item on the Anvil, and I couldn't apply it to items that are already enchanted.

**Comment by Athlaeos** [comment]
version and server software?

**Comment by JasdanVM** [comment]
Minecraft 1.20.2, Purpur server.

**Comment by Athlaeos** [comment]
could not reproduce, likely a plugin conflict, sorry!
