### ISSUE TITLE
Maven version not updated to 2.5.9

### ISSUE THREAD

**Issue by ChillyTheEevee** [Athlaeos/EnchantsSquaredRewritten#18]
The maven version of EnchantsSquaredRewritten in the pom.xml file is still on 2.5.8. This makes me sad :(
I'm writing a super quick hotfix for this, all you have to do is merge it :)

**Comment by ChillyTheEevee** [comment]
ok actually i dont think i can make a new branch to fix this :/ you just gotta change the version in the pom.xml file! you got this

**Comment by Athlaeos** [comment]
Oh, oops, lol
yeah i'll fix it real quick, will do the 1.20.5+ stuff while im at it
