### ISSUE TITLE
Compatibility problems with Booster Plugin

### ISSUE THREAD

**Issue by LyriaxDE** [Athlaeos/EnchantsSquaredRewritten#2]
Sorry for my English in advance, I'm working with a translator in the hope that it's as understandable as possible, I guess that's how they understand me best.

I have downloaded the latest version, but the flight booster from the plugin whose link I am attaching is blocked by the latest version of your plugin.
Would it be possible to make a bug fix for this?

https://www.spigotmc.org/resources/booster-spigot-unterst%C3%BCtzt-mysql.88889/

**Comment by Athlaeos** [comment]
this issue has actually already been fixed, but I didn't consider the fix significant enough to push out an update fully. I'll push out the update regardless though

**Comment by LyriaxDE** [comment]
I still have the problem, despite the update of the plugin.
The fly booster of the plugin is blocked by the new code and no longer works.
With one of the old versions it works perfectly.

**Comment by Athlaeos** [comment]
try giving your boosted players essentials.fly also, even if you don't have essentials it'll check for this permission to see if the player is allowed to fly by default. i probably ought to add my own permission for this, but yeah

**Comment by LyriaxDE** [comment]
The booster plugin allows the player to fly without /fly Permission.
He activates a "flight booster" that lets him fly. This booster is blocked by the new version.

Or what do you mean by permission exactly?

**Comment by Athlaeos** [comment]
this plugin doesn't seem to be open source, so i can't see how it works. if you join my discord server i can send you a special version where you can try to see if that version works
