### ISSUE TITLE
Flight Enchantment Breaks Elytra Upon Reaching 0 Durability

### ISSUE THREAD

**Issue by ChillyTheEevee** [Athlaeos/EnchantsSquaredRewritten#22]
The Flight enchantment's durability handling doesn't account for the special case of Elytra durability. In the base games, elytras never truly traditionally break, but are rather left in an unusable state at 1 durability until repaired. However, when the flight enchantment is used on an Elytra, this does not apply. Rather, EnchantsSquared opts to destroy the elytra as it would any other item. The ideal implementation of Flight on Elytras would be to allow the Flight enchantment to work up until the elytra breaks, and then to disable Flight on a broken elytra until it is repaired.

**Comment by ChillyTheEevee** [comment]
I realize now that by default the flight enchantment is only compatible with boots, and that I've been running a special config that allows usage of the enchantment on an Elytra. This is clearly not intended behavior, so I'm marking this issue as closed.

**Comment by ChillyTheEevee** [comment]
sorry for the inconvenience

**Comment by Athlaeos** [comment]
Oh I mean this is still a bug I think. You're right, it's an edge case I didnt consider yet. I really wished spigot provided a proper method to deal damage to items and have em break naturally

**Comment by ChillyTheEevee** [comment]
oh thanks! yup spigot is super useful for a lot of things but sometimes its just such a PAIN

**Comment by ChillyTheEevee** [comment]
One thing that's super annoying with Spigot is cloning blocks. The BlockState / BlockData stuff is SO unintuitive. I hope you never have to do it hahaha
