### ISSUE TITLE
"disable_fishing" Configuration Option Breaks Grappling Enchantment

### ISSUE THREAD

**Issue by ChillyTheEevee** [Athlaeos/EnchantsSquaredRewritten#23]
Hello there again!

Within config.yml, there are the following configuration options:

```
# Disable certain core features of the plugin in case they severely clash with other plugins, or you just don't want to use them.
disable_anvil: false # Disables custom enchantments from being able to be combined in an anvil
disable_enchanting: false # Disables custom enchantments from appearing in the enchantment table
disable_trading: false # Disables villagers from trading custom enchantments
disable_fishing: false # Disables enchanted books obtained by fishing from receiving custom enchants
disable_dungeonlootgen: false  # Disables enchanted books obtained from dungeon generated chests from receiving custom enchants
```

The issue here appears to be specifically with the disable_fishing configuration option. Within the code of EnchantsSquared, the PlayerFishListener is only registered with Spigot if disable_fishing is set to false. At first glance, this makes sense, as this would subsequentially disable all effects that EnchantsSquared has on player fishing. Thus that means that enchants squared custom enchantments cannot possibly be found within enchanted books from fishing.

However, there is an issue with this approach. Grappling (and any other future CustomEnchants that may implement TriggerOnFishingEnchantment in the future) relies on the PlayerFishListener in order to function. By not registering the PlayerFishListener when disable_fishing is set to true, you also unintentionally disable Grappling's functionality.

This does not appear to be an issue for any of the other listeners impacted by these configuration files (AnvilListener, EnchantListener, VillagerClickListener, or ChestOpenListener) because there are no Enchantments that trigger on these events.

Thank you so much for your help!

**Comment by Athlaeos** [comment]
Ah, yeah, that makes sense lol

I'll fix that up when I get home.
Also, if you're interested in testing the 1.21 version I recommend you join the discord since that's where I post them before release

**Comment by ChillyTheEevee** [comment]
Oh sick! My bad i didn't even realize there was a discord, i'll join later
