### ISSUE TITLE
passing the enchantment on a book to an item on an anvil doesn't work for me

### ISSUE THREAD

**Issue by yHenriTopper** [Athlaeos/EnchantsSquaredRewritten#25]
It works fine for me, but when I use the enchantment on a book and when I want to enchant an object with an anvil, it won't let me, and there will be no way to increase the mining capacity with the -excavation enchantment. - that is, if it is now Can you mine: 3x3, could you mine: 3x3x3? Or increase its capacity even further, from 5x5x5, 7x7x7?

**Comment by Athlaeos** [comment]
Could you test this on a separate server, with no other plugins? This bug is often reported but most of the time it's due to a conflict. 
And no, you can't (or should) increase excavation to mine that many more blocks. Block breaking like that is intense on the server
