### ISSUE TITLE
How to view description on enchanment

### ISSUE THREAD

**Issue by Artisan24** [Athlaeos/EnchantsSquaredRewritten#26]
i dont know why but in config yml every enchantments config have a description but in minecraft it not show up. please add new feature for view enchantment description

**Comment by Athlaeos** [comment]
the descriptions of each enchantment are purely visible in /es menu and /es list, they're not supposed to be visible on the item and this will not be implemented in the future either, sorry

**Comment by Artisan24** [comment]
Oh okay thanks to reply my issue

Pada Rab, 18 Sep 2024 15.35, Athlaeos ***@***.***> menulis:
