### ISSUE TITLE
remove custom enchantmentsin the enchantment table

### ISSUE THREAD

**Issue by misha275** [Athlaeos/EnchantsSquaredRewritten#29]
how to remove the possibility of custom enchantments appearing in the enchantment table

**Comment by Athlaeos** [comment]
You should really look in configs before asking such things. You can set the chance of custom enchantments occurring in an enchanting table to 0

**Comment by misha275** [comment]
I searched in the conf and didn't find it (apparently I searched poorly). Can you suggest a line
