### ISSUE TITLE
Repo not updated to version 2.5

### ISSUE THREAD

**Issue by ChillyTheEevee** [Athlaeos/EnchantsSquaredRewritten#3]
Title speaks for itself! Sorry to bother you, but I made a forked version of EnchantsSquaredRewritten for my friend to help with some niche specific problems he needed fixed and he wants to update to the newest version. Can you push version 2.5?

Also, good work on this plugin! Definitely one of our favorites <3

**Comment by ChillyTheEevee** [comment]
thanks!

**Comment by Athlaeos** [comment]
no problem, i thought i already pushed it before lol
