### ISSUE TITLE
[BUG] Lava Walker breaks every armor when the boots break

### ISSUE THREAD

**Issue by soudblox** [Athlaeos/EnchantsSquaredRewritten#6]
Steps to reproduce the bug:
1. Get a full set of armor with lava walker enchanted boots
2. Walk in lava until the boots break
3. Everything else breaks, including the helmet, chestplate, and leggings.

**Comment by Athlaeos** [comment]
Yup, you're right. For some reason I can't remember I made it so it loops through the player's armor set instead of just damaging the one item, odd. I'll do some testing and push out a fix. In the meantime, best you disable this enchantment
