### ISSUE TITLE
Integration with ItemsAdder

### ISSUE THREAD

**Issue by LastF1re** [Athlaeos/EnchantsSquaredRewritten#9]
Hello, can you integrate your enchantments with ItemsAdder? The ItemsAdder plugin does not work with the original enchants of your plugin. This is very frustrating.
![image](https://github.com/Athlaeos/EnchantsSquaredRewritten/assets/93532976/50078b73-b091-4224-b639-c1402efdf0ee)
![image](https://github.com/Athlaeos/EnchantsSquaredRewritten/assets/93532976/ad4f99b7-2470-4e0f-a516-3e4fbbfa9351)

**Comment by Athlaeos** [comment]
oh, no i can't do that. enchantssquared enchantments are not regular enchantments as you see there, they need to be added through custom nbt tags. if itemsadder doesn't support you adding them, then i'm afraid there's not much i can do

**Comment by ChillyTheEevee** [comment]
ItemsAdder does support running commands when you create an item I believe. You could probably make it run /es enchant to enchant the item whenever you create it? I could be wrong on that

**Comment by Athlaeos** [comment]
> 

The command only works if a player is executing it and if the player is holding that item. This command could work, but they'd have to create a virtual fake player who then executes the command and then takes that item and gives it to you. I'd be impressed if they went through the trouble to do that, but I doubt it
